# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160416_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
