# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160430_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='cat',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cat',
            field=models.ManyToManyField(to='blog.BlogPostCategory'),
        ),
    ]
