# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160506_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='cat',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.BlogPostCategory'),
        ),
    ]
