# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160506_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.BlogPostCategory'),
        ),
    ]
