# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20160508_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('extension', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='blogpostcategory',
            name='ex',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='blog.Extension'),
        ),
    ]
