# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20160508_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostcategory',
            name='ex',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='cat',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cat',
            field=models.ManyToManyField(related_name='posts', to='blog.BlogPostCategory'),
        ),
        migrations.DeleteModel(
            name='Extension',
        ),
    ]
